root: true

plugins:
  - jest

env:
  node: true
  jest: true
  browser: true

extends:
  - "airbnb-base"
  - "plugin:jest/recommended"

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  no-console: 0
  import/extensions: 0